import "./globals.css";
import { AuthProvider } from "./Provider";
import { Roboto } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700"],
  subsets: ["latin"],
})

export const metadata = {
  title: "Kratos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} no-scrollbar`}>
        <AuthProvider>
          <Navbar />
          <main className="pt-[84px]">{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
